### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by BDrescher** [chili-epfl/qml-cvcamera#2]
Hey,
I just compiled your plugin and opencv 3.0.0 alpha. Sadly when i try to start a program using your plugin - e.g. your samples - it immediatelly crashes with "Segmentationfault".
Now i wondere wether the problem occurs in your plugin or the opencv part.
Do you know how i can check that out?
Kind Regards

System: Raspberry Pi using jessie up to date freshly installed

€: I just checked the make output file of opencv and it has several warnings about array-using out of it boundaries. in:
modules/imgproc/src/contours.cpp
modules/imgproc/test/test_convull.cpp

**Comment by severin-lemaignan** [comment]
@arcFT Thanks for your report. Cool to know that you've tried it on a raspberrypi.

As a first sanity check, can you make sure you're able to grab frames in opencv (ie, without the Qt/qml part)?

Something as simple as that should do:

``` c++
#include <opencv2/videoio.hpp>
#include <iostream>

using namespace std;
using namespace cv;


int main(int argc, char **argv)
{
    Mat frame;

    VideoCapture video_in(1);

    if(!video_in.isOpened()) {
        cerr << "Couldn't open camera" << endl;
        return 1;
    }

    while(true)
    {
        video_in >> frame;
    }
    return 0;
}

```

**Comment by ayberkozgur** [comment]
It would be also very fast to determine where is the problem by building both `qml-cvcamera` and `opencv` in debug mode (with `-g`) and running your application through `gdb`.

**Comment by BDrescher** [comment]
@ayberkozgur Thank you for that hint. Sadly as im compiling everything I would like to not need that as compiling opencv needs about 1 day at all

@severin-lemaignan I have to thank for that plugin you made.
The test-programm does not end up in Segmentationfault. 

I debugged my application and it lead me to the error. I forgot to completely purge libopencv before installing version 3.0.0 and that made your plugin be compiled with version 2.4.9 and crashing when creating Cv::Mat.
It runs fine now.

Thanks for your fast support! I'm glad i can finally use the raspicam in my own project.

**Comment by ayberkozgur** [comment]
Wow, a day to compile opencv on rpi?! I've never done it but it still sounds like too much. I'm almost sure that you have some background process hogging your cpu. Anyway, you can always disable opencv modules and features you don't need (for qml-cvcamera, more than half) via `ccmake` to speed up the build.

Now that you no longer have segfaults, closing ths issue.

**Comment by severin-lemaignan** [comment]
@ayberkozgur For the record, I'm not surprised at all that opencv takes ~1 day to compile on the raspi...

**Comment by ayberkozgur** [comment]
As @severin-lemaignan pointed out the other day, the fact that rpi is heavily accessing the SD card during cmake/make might have a considerable impact on the build time. You might want to instruct cmake/make to use a tmpfs during build to speed things up.
